run:
  name: baseline

ROMS: 
  yaml_loc: /home/ansju8054/Documents/Code/havvind-mix/mixtest_3d/roms

files:
  grd: mixtest_3d_grd.nc
  ini: mixtest_3d_ini.nc
  frc: mixtest_3d_frc.nc
  clm: mixtest_3d_clm.nc
  nud: mixtest_3d_nud.nc
  his: mixtest_3d_his.nc
  

grid:
  Lm: 120        # number of interior xi points
  Mm: 12        # number of interior eta points
  N: 40
  H0: 150.0     # uniform depth (m)
  DX: 800.0     # grid spacing xi (m)
  DY: 800.0     # grid spacing eta (m)

GLS:            # gen closure
  P: 2.0
  M: 1.0
  N: -0.67
  Kmin: 1.0
  Pmin: 1.0
  CMU0: 0.527
  C1: 1.0
  C2: 1.22
  C3M: 0.05
  C3P : 1.0
  SIGK: 0.8
  SIGP: 1.07

vertical:
  Vtransform: 2
  Vstretching: 5
  THETA_S: 5.0
  THETA_B: 4.0
  HC: 100.0

time_stepping:
  NTIMES: 15120  # 60480 for month, 15120 for week
  DT: 40.0
  NHIS: 90

phys:
  F0: 0       # Coriolis (s^-1)
  RDRG2: 0    # Quadratic bottom drag (e-3). Norkyst uses 3

structure:
  str_a: 0.0001           # about 5 turbines with a diameter of 12 m per grid cell
  depth_zero_below: 1.0e9 # set to a large number to keep full column non-zero
  CD: 0.63
  c4: 0.44                # strong mixing
  xi_limits: [70,80]      # xi grid cell limits for turbine placement


initial:
  ocean_time_seconds: 0.0   # time stamp for the IC file

  # Temperature profile
  T0: 20.0     # Surface temperatur
  dT: 10.0     # temperature change across thermocline
  zt: 40.0     # depth of thermocline center
  ht: 10.0     # thickness of thermocline

  # Salinity (constant)
  salt_S0: 35.0

  # Velocity profile
  u_type: uniform
  u0: 0.15

  v0: 0.0

forcing:
  dt_frc: 86400.0   # forcing time step (s); ROMS interpolates between snapshots

  # Surface wind stress (replace placeholder values with analytical parameters)
  sustr_tau0: 0.1    # zonal surface stress (N/m^2), placeholder constant
  svstr_tau0: 0.0    # meridional surface stress (N/m^2), placeholder constant


nudging:
  tracer:
    zone_start: 0
    taper_width: 10
    core_width: 30
    tau_core_days: 0.25
    tau_edge_days: 10.0

  m3:
    zone_start: 0
    taper_width: 10
    core_width: 40
    tau_core_days: 0.25
    tau_edge_days: 10.0

